config/routes.rb
Personalitytest::Application.routes.draw do
  post "results" => 'home#results', as: "results"
  root :to => 'home#index'
end

app/models/answer.rb
class Answer
  include ActiveAttr::Model

  attribute :answers
  validate :size_of_answers

  def results
    types = {e: 0, i: 0, n: 0, s: 0, f: 0, t: 0, p: 0, j: 0}
    self.answers.each do |number, answer|
      letter = QUESTIONS[number.to_i-1][answer]["letter"].to_sym
      types[letter] += 1
    end

    ei = {e: types[:e], i: types[:i]}
    ns = {n: types[:n], s: types[:s]}
    ft = {f: types[:f], t: types[:t]}
    pj = {p: types[:p], j: types[:j]}

    type = ""
    [ei, ns, ft, pj].each do |group|
      type << group.sort_by {|key, value| value}.reverse.first.first.to_s.upcase # OMGWTFBBQ, this is disgusting
    end
    type
  end

  private
    def size_of_answers
      QUESTIONS.each_with_index do |question, i|
        errors[:base] << "Please answer question #{i+1}" if self.answers.nil? or self.answers["#{i}"].nil?
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :setup

  def index
  end

  def results
    if @answer.valid?
      @personality_type = @answer.results
    else
      render action: :index
    end
  end

  private
    def setup
      @answer = Answer.new(answers: params[:answers])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h2 Take the test!

= form_tag results_path do
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this test from being saved:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg
  %ol.questions
    - QUESTIONS.each_with_index do |question, i|
      %li
        = question["text"]
        %ul.answers
          %li
            = radio_button_tag "answers[#{i}]", "a", (@answer.answers["#{i}"] == "a" rescue false)
            = question["a"]["text"]
          %li
            = radio_button_tag "answers[#{i}]", "b", (@answer.answers["#{i}"] == "b" rescue false)
            = question["b"]["text"]
  = submit_tag

app/views/home/results.html.haml
%h2 Results

%p Your personality type is: #{@personality_type}!

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Personalitytest
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header.container
      .span12
        %h1 Personality Test
    #main.container
      .span12
        = yield